import type { DiscordArticle } from './discord-articles';
export const discordCompatibilityArticles: DiscordArticle[] = [
  {
    slug: 'voice-client-outdated',
    category: 'connection',
    title: 'Discordの古いバージョンで通話できない｜更新できない時の対処',
    shortTitle: '古いバージョンで通話できない',
    seoTitle: 'Discordの古いバージョンで通話できない｜更新確認・DAVE対応',
    metaDescription: 'Discordの通話に必要な最低バージョンと更新前後の確認方法。更新できない・番号が変わらない時の手順、アプリとブラウザの結果別判断表、Update Failedなどの確認先を解説します。',
    symptom: 'チャットは使えるのに通話へ参加できない、古いバージョンの警告が出る、更新しても同じ番号のままの場合の手順です。',
    target: 'Windows版Discord・PCブラウザ版／バージョン非対応が疑われる場合',
    conclusion: 'Discordは2026年3月2日以降の通話に暗号化対応を必須としています。まず更新前のバージョンを控え、完全終了・更新後に同じ画面で再確認します。更新できなければ現行ブラウザで同じ通話を試し、アプリだけ失敗するのか、両方で接続できないのかで次の手順を選びます。',
    quickFixes: [
      'ユーザー設定の最下部で、更新前のバージョン表示全体を記録する',
      'Discordを完全終了して再起動し、更新後の版と通話結果を確認する',
      '更新失敗ならブラウザ版を比較し、エラー表示に合う手順へ進む',
    ],
    showStatusCheck: false,
    diagnosisTitle: 'アプリとブラウザの通話結果で選ぶ判断表',
    diagnosisIntro: '同じPC・回線・アカウント・通話先で、片方から退出してからもう片方を試します。「チャットが開いた」ではなく「通話に参加できたか」で比較してください。',
    diagnosis: [
      { symptom: '古いバージョンの警告／Windows版が1.0.9164未満', check: '更新前の番号を記録して完全終了・更新', causeIndex: 1 },
      { symptom: '再起動後も番号が変わらない', check: '最低条件、表示全体、起動したアプリを確認', causeIndex: 2 },
      { symptom: 'Update Failed／更新ループ／Installation has failed', check: 'ブラウザで通話を確保し、表示別の記事へ', causeIndex: 2 },
      { symptom: 'アプリは失敗、更新済みブラウザは通話できる', check: 'アプリの更新・起動先・導入状態を優先', causeIndex: 4 },
      { symptom: 'アプリは通話できる、ブラウザだけ失敗', check: 'ブラウザの再起動・サイト権限・表示エラーを確認', causeIndex: 3 },
      { symptom: '両方とも対応版だが通話に参加できない', check: '障害・RTC接続・No Route・チャンネル権限へ', causeIndex: 4 },
      { symptom: '参加できたが無音／音楽Botだけ動かない', check: '入出力設定またはBot提供者の対応状況へ', causeIndex: 4 },
    ],
    causes: [
      {
        title: '更新前の版を記録し、完全終了して更新する',
        description: '公式の最低条件はWindows版1.0.9164、Firefox 142です。Chrome・Edgeは86と案内されていますが、これらは通話の最低条件であり、今使うべき最新版ではありません。利用可能な更新を適用してください。',
        actions: [
          'Discordの歯車アイコン→ユーザー設定を開き、設定パネルの最下部にあるバージョン表示全体を控える。複数の番号がある場合は一部分だけを書き写さず、画面も記録する。',
          'Windows通知領域のDiscordアイコンを右クリックして終了する。必要ならCtrl＋Shift＋Escでタスクマネージャーを開き、Discordが残っていないか確認する。',
          'スタートメニューから普段使っているDiscordを起動し、更新処理が終わってチャット画面になるまで待つ。Update Failedなどが出たら、その文言を記録してSTEP 2へ。',
          '同じ設定画面を再び開き、更新後の版を記録する。同じ通話へ参加し、古い版の警告・接続結果・相互に声が聞こえるかを確認する。',
        ],
        note: 'DAVEはDiscordの音声・映像を暗号化する仕組みです。暗号化を無効にして古い版を使い続ける手順ではなく、対応版での復旧を進めます。',
      },
      {
        title: '番号が変わらない・更新できない時は、表示と起動先を確認する',
        description: '同じ番号でも、既に利用可能な最新版なら更新失敗とは限りません。一方、最低条件未満や非対応の警告が続く場合は、更新済みと判断しないでください。',
        actions: [
          '更新前後で同じアプリ・同じ設定欄を見ているか確認する。通常版のほかにPTB・Canaryが入っている場合は、アプリ名も記録し、更新したものと起動したものを取り違えていないか確認する。',
          'タスクバーやデスクトップの古いショートカットではなく、スタートメニューで対象のDiscordを選び直す。同じ警告が出るか確認し、PC再起動後にも版を再確認する。',
          'Update Failedや更新ループなら関連記事「Update Failed・更新ループ」へ。アプリ・ブラウザ・回線の比較から進め、最初からAppDataを削除しない。',
          '更新処理が進まず新しいインストーラーが必要な場合は、Discord公式ダウンロードページからWindows版を取得する。再インストール前にログイン方法・二段階認証の利用手段と音声設定を確認する。',
          'インストーラーで「Installation has failed」が出るなら同名の関連記事へ。OS非対応や管理者による制限が表示された場合は、その条件を確認し、対応端末または端末管理者への相談に切り替える。',
        ],
        note: '更新できない間はSTEP 3の公式ブラウザ版で同じ通話を試せます。ただしブラウザもOSも対応が必要で、古いPCなら必ず回避できるわけではありません。',
      },
      {
        title: 'ブラウザ自体を更新・再起動して、同じ通話を試す',
        description: 'Discordのページ再読み込みと、ブラウザ本体の更新は別です。ブラウザを再起動した後、公式の https://discord.com/app を開いて比較します。',
        actions: [
          'Chromeは右上の「︙」→「ヘルプ」→「Google Chromeについて」で更新状態と番号を確認し、求められたら再起動する。再起動後も同じ画面で確認する。',
          'Mozilla公式サイトから入れたFirefoxは、メニューの「ヘルプ」→「Firefoxについて」で更新を確認する。Microsoft Storeから入れた版はStoreで更新する。更新後の再起動を完了させ、142以上かと更新エラーの有無を確認する。',
          'Edgeを使う場合も「ヘルプとフィードバック」→「Microsoft Edgeについて」で更新状態を確認し、必要な再起動を済ませる。',
          'アプリ版の通話から退出し、ブラウザで同じアカウント・同じ通話先へ参加する。マイクの許可を求められたら、discord.comへの許可と使うマイクを確認する。',
          '「参加できない」「参加できるが声が届かない」「相互に話せる」のどれかを記録する。ブラウザだけ無音なら、アドレスバー付近のサイト設定でマイク許可とDiscordの入出力設定を確認する。',
        ],
        note: '記録例：「アプリは古い版の警告、Chromeは相互通話OK」ならアプリ側を優先。「両方RTC接続中」なら接続経路の確認へ進みます。これは判断例であり、実機検証結果ではありません。',
      },
      {
        title: '比較結果に合わせ、更新・接続・音声・Botを分けて対処する',
        description: '対応版になった後も症状が残る場合、すべてをDAVEの問題として扱わず、どこまでできるかで確認先を変えます。',
        actions: [
          'ブラウザだけ通話できるなら、いったんブラウザを使い、STEP 2でアプリの更新・起動先・導入エラーを確認する。この結果だけで回線の影響を完全に否定しない。',
          'アプリだけ通話できるなら、ブラウザの更新・再起動・サイトのマイク許可を確認する。ブラウザに古い版の警告が残る場合はOSの対応状況も調べる。',
          '両方でRTC接続中やNo Routeになるなら、Discord Statusを確認し、該当する接続エラーの記事へ進む。特定チャンネルだけなら管理者へ「接続」「発言」権限を確認してもらう。',
          '通話へ入れるが声が聞こえない場合は、マイク・スピーカーのミュートと「音声・ビデオ」の入出力先を確認する。相手の声だけ聞こえなければ関連記事の出力側の手順へ。',
          '人同士は話せて音楽Botだけ失敗するなら、Bot提供者のDAVE対応・障害情報を確認する。利用者のアプリ再インストールを繰り返しても、Bot側の未対応は修正できない。',
        ],
      },
    ],
    ifNotFixed: 'Discordサポートへ「Windowsの版／更新前後のDiscord表示全体／通常版・PTBなどの種類／ブラウザ名と版／同じ通話の比較結果／警告全文と発生時刻」を送ってください。更新エラーなのか、更新後の通話エラーなのかを分けると状況を伝えやすくなります。',
    faqs: [
      { question: '番号が変わらないと更新失敗ですか？', answer: '必ずしもそうではありません。既に最新の場合や、見ている番号の種類が違う場合があります。同じアプリの同じ設定欄で表示全体を比べ、最低条件・更新エラー・通話結果を合わせて判断します。' },
      { question: 'チャットが開けば対応版だと判断できますか？', answer: 'できません。文字チャットと音声・映像通話の条件は異なります。同じ通話に参加し、相互に声が届くところまで確認してください。' },
      { question: '最低バージョンを入れれば十分ですか？', answer: '最低条件は通話対応の目安です。古い版を指定して入れ直すのではなく、その端末で利用可能な現行版へ更新してください。OSの互換性も確認対象です。' },
      { question: 'アプリを更新できない間も通話できますか？', answer: '対応ブラウザとOSなら公式ブラウザ版を試せます。そこで通話できる場合は一時的に使い、アプリの更新問題を別に解決します。ブラウザでも失敗する場合は表示に合う接続・権限の確認へ進みます。' },
    ],
    sources: [
      { label: 'Discord公式：通話に必要な最低バージョン', url: 'https://support.discord.com/hc/en-us/articles/38025123604631-Minimum-Client-Version-Requirements-for-Voice-Chat' },
      { label: 'Discord公式：トラブルシューティングガイド', url: 'https://support.discord.com/hc/en-us/articles/31623498041623-Discord-Troubleshooting-Guide' },
      { label: 'Discord公式：ダウンロード', url: 'https://discord.com/download' },
      { label: 'Google公式：Google Chromeを更新する', url: 'https://support.google.com/chrome/answer/95414?hl=ja' },
      { label: 'Mozilla公式：Firefoxを最新リリースに更新する', url: 'https://support.mozilla.org/ja/kb/update-firefox-latest-release' },
      { label: 'Microsoft公式：Microsoft Edgeの更新設定', url: 'https://support.microsoft.com/en-us/topic/microsoft-edge-update-settings-af8aaca2-1b69-4870-94fe-18822dbb7ef1' },
      { label: 'Discord Status（公式障害情報）', url: 'https://discordstatus.com/' },
    ],
    related: ['update-failed', 'installation-failed', 'rtc-connecting', 'no-route', 'cant-hear-voice', 'bot-not-responding'],
    checkedAt: '2026-09-28',
    status: 'verified',
    ogTitle: 'Discordの古い版で通話できない',
    ogSteps: ['更新前後の番号を確認', '完全終了→更新→再確認', 'アプリ／ブラウザで比較', '更新失敗と接続不良を分ける'],
  },
];
