import type { Locale } from '@/lib/i18n';
export type MyGamesLocale = 'ja' | Locale;
export const myGamesPath = (locale: MyGamesLocale) =>
  `${locale === 'ja' ? '' : `/${locale}`}/my-games`;
export const myGamesCopy = {
  ja: {
    title: '遊ぶゲームの対処法を、自分の一覧に。',
    name: 'マイゲーム',
    lead: 'ゲームを1本選ぶだけ。起動しない・落ちる・重いときの解決記事を、次回もここからすぐ開けます。',
    privacy:
      '無料・アカウント不要。このブラウザだけに保存され、別の端末には同期しません。サイトデータを消すと選択も消えます。',
    choose: 'まず、遊んでいるゲームを選ぶ',
    search: 'ゲーム名で絞り込む',
    placeholder: '例：モンハン、Elden Ring',
    hint: '選ぶとすぐ保存。最大10本まで、いつでも外せます。',
    selected: '選択中',
    add: '追加',
    remove: '外す',
    preview: '保存前に、できることを見てみる',
    example: '例：',
    previewNote:
      '選ぶと、このようなゲーム別の解決記事が自分の一覧にまとまります。',
    guides: 'このゲームの解決記事',
    savedTitle: 'あなたのゲームから、解決手順へ',
    empty:
      'まだゲームを選んでいません。上から1本選ぶと、ここに解決記事が表示されます。',
    noResults: '一致するゲームがありません。別の名前で検索してください。',
    noGuides: '個別の解決記事は準備中です。',
    hub: 'ゲーム総合ガイド',
    ja: '（日本語）',
    success: 'このブラウザに保存しました。マイゲームから解決記事を開けます。',
    removed: 'マイゲームから外しました。',
    error: '保存できませんでした。ブラウザの保存設定を確認してください。',
    corrupt: '保存データを読み取れないため、変更していません。',
    limit: '最大10本です。選択を減らしてから追加してください。',
    loading: '保存したゲームを確認しています…',
    open: '自分のゲームを選ぶ',
    return: 'マイゲームを開く',
    news: '公式のお知らせ（Steam・30日以内）',
    newsNote: '取得できたお知らせだけを表示します。自動通知はありません。',
    original: '公式発表の原文',
    savedLink: '保存した記事・解決ノートへ',
    count: '保存済み',
  },
  en: {
    title: 'Your games. Their fixes. One place.',
    name: 'My Games',
    lead: 'Pick a game to keep its troubleshooting guides together. Come back here when it won’t launch, crashes, or runs poorly.',
    privacy:
      'Free. No account needed. Saved only in this browser, with no cross-device sync. Clearing site data removes your choices.',
    choose: 'Start with a game you play',
    search: 'Filter by game name',
    placeholder: 'Try Monster Hunter or Elden Ring',
    hint: 'Each choice saves immediately. Keep up to 10 games and remove any at any time.',
    selected: 'Selected',
    add: 'Add',
    remove: 'Remove',
    preview: 'See what you get before saving',
    example: 'Example: ',
    previewNote: 'Choose a game to bring guides like these into your own list.',
    guides: 'Troubleshooting guides',
    savedTitle: 'Your games, ready when you need a fix',
    empty:
      'No games saved yet. Choose one above to see its troubleshooting guides here.',
    noResults: 'No matching games. Try another name.',
    noGuides: 'Individual troubleshooting guides are not available yet.',
    hub: 'Game guide',
    ja: ' (Japanese)',
    success:
      'Saved in this browser. Open My Games to find its troubleshooting guides.',
    removed: 'Removed from My Games.',
    error: 'Could not save. Check this browser’s storage settings.',
    corrupt: 'Saved data could not be read. Nothing was changed.',
    limit: 'You can save up to 10 games. Remove one before adding another.',
    loading: 'Checking saved games…',
    open: 'Choose my games',
    return: 'Open My Games',
    news: 'Official Steam news from the last 30 days',
    newsNote:
      'Only retrieved announcements are shown. No automatic notifications.',
    original: 'Original announcement language',
    savedLink: 'Saved articles and solution notes (Japanese)',
    count: 'saved',
  },
  zh: {
    title: '把常玩的游戏和解决方法，放在一起。',
    name: '我的游戏',
    lead: '选一个游戏，就能集中查看它的故障排查指南。下次遇到无法启动、崩溃或卡顿时，直接从这里打开。',
    privacy:
      '免费，无需账号。仅保存在当前浏览器，不会跨设备同步。清除网站数据会删除所选游戏。',
    choose: '先选一个你常玩的游戏',
    search: '按游戏名称筛选',
    placeholder: '例如：Monster Hunter、Elden Ring',
    hint: '选择后立即保存，最多10款，随时可以移除。',
    selected: '已选择',
    add: '添加',
    remove: '移除',
    preview: '保存前，先看看效果',
    example: '示例：',
    previewNote: '选择游戏后，这样的游戏专属指南就会出现在你的列表中。',
    guides: '故障排查指南',
    savedTitle: '你的游戏，需要时直接查看解决方法',
    empty: '还没有保存游戏。从上方选择一款，它的故障排查指南就会显示在这里。',
    noResults: '没有匹配的游戏，请试试其他名称。',
    noGuides: '暂时没有单独的故障排查指南。',
    hub: '游戏综合指南',
    ja: '（日语）',
    success: '已保存到当前浏览器。可以从我的游戏打开故障排查指南。',
    removed: '已从我的游戏中移除。',
    error: '无法保存，请检查浏览器的存储设置。',
    corrupt: '无法读取已保存的数据，未进行任何更改。',
    limit: '最多保存10款，请先移除一款再添加。',
    loading: '正在读取已保存的游戏…',
    open: '选择我的游戏',
    return: '打开我的游戏',
    news: 'Steam官方公告（最近30天）',
    newsNote: '仅显示成功获取的公告，不提供自动通知。',
    original: '公告原文',
    savedLink: '已保存的文章和解决笔记（日语）',
    count: '已保存',
  },
  es: {
    title: 'Tus juegos y sus soluciones, en un solo lugar.',
    name: 'Mis juegos',
    lead: 'Elige un juego para reunir sus guías de solución de problemas. Vuelve aquí cuando no arranque, se cierre o vaya lento.',
    privacy:
      'Gratis y sin cuenta. Se guarda solo en este navegador, sin sincronización entre dispositivos. Al borrar los datos del sitio, se eliminan tus selecciones.',
    choose: 'Empieza con un juego al que juegues',
    search: 'Filtrar por nombre del juego',
    placeholder: 'Prueba Monster Hunter o Elden Ring',
    hint: 'Cada selección se guarda al instante. Puedes guardar hasta 10 juegos y quitarlos cuando quieras.',
    selected: 'Seleccionado',
    add: 'Añadir',
    remove: 'Quitar',
    preview: 'Mira qué obtienes antes de guardar',
    example: 'Ejemplo: ',
    previewNote:
      'Elige un juego para reunir guías como estas en tu propia lista.',
    guides: 'Guías de solución de problemas',
    savedTitle: 'Tus juegos, listos cuando necesites una solución',
    empty:
      'Aún no has guardado juegos. Elige uno arriba para ver aquí sus guías.',
    noResults: 'No hay juegos que coincidan. Prueba otro nombre.',
    noGuides: 'Todavía no hay guías específicas de solución de problemas.',
    hub: 'Guía del juego',
    ja: ' (japonés)',
    success: 'Guardado en este navegador. Abre Mis juegos para ver sus guías.',
    removed: 'Eliminado de Mis juegos.',
    error:
      'No se pudo guardar. Revisa los ajustes de almacenamiento del navegador.',
    corrupt: 'No se pudieron leer los datos guardados. No se ha cambiado nada.',
    limit: 'Puedes guardar hasta 10 juegos. Quita uno antes de añadir otro.',
    loading: 'Consultando los juegos guardados…',
    open: 'Elegir mis juegos',
    return: 'Abrir Mis juegos',
    news: 'Noticias oficiales de Steam de los últimos 30 días',
    newsNote:
      'Solo se muestran los anuncios obtenidos. No hay notificaciones automáticas.',
    original: 'Idioma original del anuncio',
    savedLink: 'Artículos guardados y notas de soluciones (japonés)',
    count: 'guardados',
  },
} as const;
