export type SupportLocale = 'ja' | 'en' | 'zh' | 'es';
const en = {
  heading: 'Continue this issue',
  privacy:
    'Private notes stay in this browser. Nothing is sent automatically. Back up important notes on My Page. PC settings are never changed by this site.',
  choose: 'Issue notebook',
  none: 'Choose an existing issue',
  create: 'Save a new issue',
  edit: 'Edit issue',
  save: 'Save note',
  cancel: 'Cancel',
  saved: 'Saved in this browser.',
  error:
    'Could not read or save. Your changes are not saved. Check browser storage and try again; existing records are preserved.',
  title: 'Issue title',
  game: 'Game',
  other: 'PC / Discord / Other',
  status: 'Status',
  investigating: 'Investigating',
  unresolved: 'Unresolved',
  resolved: 'Resolved',
  diagnosis: 'Symptoms and diagnosis',
  settings: 'Settings changed / solution',
  notes: 'Results and notes',
  completed: 'Previously checked steps',
  local: 'Private: do not enter passwords or authentication codes.',
  history: 'Attempts across articles',
  noAttempts:
    'No attempts recorded. Select a step and its result to save it. Older checked steps remain in your note.',
  step: 'Step attempted',
  result: 'Result',
  tried: 'Tried; result not confirmed',
  record: 'Record result',
  resume: 'Open recorded step',
  active:
    'The selected issue continues across articles. Check this selection before recording a different problem.',
  rollback: 'Temporary settings checklist',
  setting: 'Setting changed',
  original: 'Original value',
  restore: 'How to restore it',
  pending: 'Needs restoring',
  restored: 'Restored',
  kept: 'Keep: identified as the cause',
  add: 'Add setting',
  noSettings: 'No temporary settings recorded.',
  summary: 'Support summary: preview and copy',
  include: 'Choose what to include',
  includeGame: 'Game',
  includeSymptoms: 'Symptoms (original text)',
  includePc: 'PC specifications',
  includeAttempts: 'Attempts and results (original text)',
  includeNotes: 'Settings and notes (original text)',
  language: 'Summary language',
  review:
    'Names, paths and account information are excluded by default because free text is unchecked. If you include it, review and remove private details in the preview before copying. Automatic redaction cannot guarantee privacy.',
  untranslated:
    'User-entered text and step titles below are original text, not automatically translated.',
  preview: 'Editable preview',
  copy: 'Copy text',
  copied: 'Copied. Paste it yourself into Discord, Reddit or official support.',
  copyError: 'Copy failed. Select and copy the preview manually.',
  updates: 'Verified developments for unresolved issues',
  emptyUpdates:
    'No new verified developments match your saved unresolved issues. This does not mean the problem has been fixed.',
  official: 'Official fix',
  workaround: 'Verified workaround',
  evidence: 'Evidence',
  verified: 'Verified on',
  mark: 'Mark these updates as read',
  updateHint:
    'Separate from general Steam news. Matches the saved game and article symptom; a publication date alone is never a fix. Results can depend on version and environment.',
};
export const supportCopy: Record<SupportLocale, typeof en> = {
  en,
  ja: {
    heading: '同じ問題の続きから',
    privacy:
      '記録はこのブラウザ内だけに保存し、自動送信しません。大切な記録はマイページでバックアップしてください。PC設定を自動操作することはありません。',
    choose: '問題のノート',
    none: '保存済みの問題を選択',
    create: '診断結果・設定を保存',
    edit: '問題を編集',
    save: 'ノートに保存する',
    cancel: 'キャンセル',
    saved: 'このブラウザに保存しました。',
    error:
      '読み込み・保存ができませんでした。変更は未保存です。ブラウザの保存領域を確認して再試行してください。既存の記録は保全しています。',
    title: '記録のタイトル',
    game: 'ゲーム・対象',
    other: 'PC・Windows／Discord／その他',
    status: '現在の状態',
    investigating: '確認中',
    unresolved: '未解決',
    resolved: '解決済み',
    diagnosis: '症状・診断結果',
    settings: '変更した設定・解決した方法',
    notes: '結果・メモ',
    completed: '以前に確認した手順',
    local: '非公開の記録です。パスワード・認証コードは書かないでください。',
    history: '記事をまたいだ試行履歴',
    noAttempts:
      '試行履歴はまだありません。手順と結果を選んで保存してください。以前の確認済み手順はノートに残っています。',
    step: '試した手順',
    result: '結果',
    tried: '試行済み・結果未確認',
    record: '結果を記録',
    resume: '記録した手順を開く',
    active:
      '選択した問題を記事間で引き継ぎます。別の問題を記録するときは選択を確認してください。',
    rollback: '一時変更した設定の戻し忘れチェック',
    setting: '変更した設定',
    original: '元の設定値',
    restore: '元に戻す方法',
    pending: '戻す必要あり',
    restored: '戻した',
    kept: '原因なので維持',
    add: '設定を追加',
    noSettings: '一時変更した設定の記録はありません。',
    summary: '相談用まとめのプレビューとコピー',
    include: '共有する項目',
    includeGame: 'ゲーム名',
    includeSymptoms: '症状（原文）',
    includePc: 'PC構成',
    includeAttempts: '試した対処と結果（原文）',
    includeNotes: '設定・メモ（原文）',
    language: 'まとめの言語',
    review:
      '自由文は初期状態では含めず、個人名・ファイルパス・アカウント情報を除外します。含める場合はプレビューで個人情報を削除してからコピーしてください。自動マスキングで完全に除去できるとは限りません。',
    untranslated: '以下の自由文・手順名は原文です。自動翻訳していません。',
    preview: '編集できるプレビュー',
    copy: '文章をコピー',
    copied:
      'コピーしました。Discord・Reddit・公式サポートへご自身で貼り付けてください。',
    copyError:
      'コピーできませんでした。プレビューの文章を選択して手動でコピーしてください。',
    updates: '未解決の症状に関する確認済みの進展',
    emptyUpdates:
      '保存した未解決の症状に一致する新しい確認済み情報はありません。問題が修正されたという意味ではありません。',
    official: '公式修正',
    workaround: '検証済み対処法',
    evidence: '根拠',
    verified: '確認日',
    mark: '表示した更新を確認済みにする',
    updateHint:
      '一般Steamニュースとは別です。保存したゲームと記事の症状を対応付け、記事の更新日だけで修正とは判定しません。適用条件・バージョンを確認してください。',
  },
  zh: {
    heading: '继续处理同一个问题',
    privacy:
      '记录仅保存在此浏览器中，不会自动发送。请在个人页面备份重要记录。本站不会自动更改电脑设置。',
    choose: '问题笔记',
    none: '选择已保存的问题',
    create: '保存新问题',
    edit: '编辑问题',
    save: '保存笔记',
    cancel: '取消',
    saved: '已保存在此浏览器中。',
    error:
      '无法读取或保存，修改尚未保存。请检查浏览器存储后重试；原有记录已保留。',
    title: '问题标题',
    game: '游戏',
    other: '电脑／Discord／其他',
    status: '状态',
    investigating: '排查中',
    unresolved: '未解决',
    resolved: '已解决',
    diagnosis: '症状与诊断结果',
    settings: '更改的设置／解决方法',
    notes: '结果与备注',
    completed: '之前检查过的步骤',
    local: '私人记录：请勿输入密码或验证码。',
    history: '跨文章的尝试记录',
    noAttempts:
      '尚无尝试记录。请选择步骤和结果并保存。旧的已检查步骤仍保留在笔记中。',
    step: '尝试的步骤',
    result: '结果',
    tried: '已尝试，结果未确认',
    record: '记录结果',
    resume: '打开已记录的步骤',
    active: '所选问题会在文章间保留。记录其他问题前请确认选择。',
    rollback: '临时设置还原清单',
    setting: '更改的设置',
    original: '原始值',
    restore: '还原方法',
    pending: '需要还原',
    restored: '已还原',
    kept: '确认为原因，保留修改',
    add: '添加设置',
    noSettings: '没有临时设置记录。',
    summary: '求助摘要：预览与复制',
    include: '选择要分享的项目',
    includeGame: '游戏名',
    includeSymptoms: '症状（原文）',
    includePc: '电脑配置',
    includeAttempts: '尝试与结果（原文）',
    includeNotes: '设置与备注（原文）',
    language: '摘要语言',
    review:
      '默认不包含自由文本，以排除姓名、文件路径和账户信息。如需包含，请在预览中删除隐私信息后再复制。自动遮蔽无法保证完全去除隐私信息。',
    untranslated: '以下用户文本及步骤名称为原文，未经自动翻译。',
    preview: '可编辑的预览',
    copy: '复制文本',
    copied: '已复制。请自行粘贴到 Discord、Reddit 或官方支持渠道。',
    copyError: '复制失败。请选中预览文本并手动复制。',
    updates: '未解决症状的已核实进展',
    emptyUpdates:
      '没有与已保存的未解决症状相符的新核实信息。这不代表问题已经修复。',
    official: '官方修复',
    workaround: '已验证的解决方法',
    evidence: '依据',
    verified: '核实日期',
    mark: '将这些更新标记为已读',
    updateHint:
      '与一般 Steam 新闻分开显示。按已保存的游戏和文章症状匹配，不会仅凭文章更新日期判断修复。请确认适用版本与环境。',
  },
  es: {
    heading: 'Continuar con este problema',
    privacy:
      'Las notas se guardan solo en este navegador. No se envían automáticamente. Haz una copia de las notas importantes en Mi página. El sitio nunca modifica los ajustes del PC.',
    choose: 'Nota del problema',
    none: 'Seleccionar un problema guardado',
    create: 'Guardar un problema nuevo',
    edit: 'Editar problema',
    save: 'Guardar nota',
    cancel: 'Cancelar',
    saved: 'Guardado en este navegador.',
    error:
      'No se pudo leer o guardar. Los cambios no están guardados. Revisa el almacenamiento y vuelve a intentarlo; se conservan los registros existentes.',
    title: 'Título del problema',
    game: 'Juego',
    other: 'PC / Discord / Otros',
    status: 'Estado',
    investigating: 'En investigación',
    unresolved: 'Sin resolver',
    resolved: 'Resuelto',
    diagnosis: 'Síntomas y diagnóstico',
    settings: 'Ajustes modificados / solución',
    notes: 'Resultados y notas',
    completed: 'Pasos comprobados anteriormente',
    local:
      'Nota privada: no introduzcas contraseñas ni códigos de autenticación.',
    history: 'Intentos entre artículos',
    noAttempts:
      'No hay intentos registrados. Selecciona un paso y su resultado para guardarlo. Los pasos antiguos se conservan en la nota.',
    step: 'Paso probado',
    result: 'Resultado',
    tried: 'Probado; resultado sin confirmar',
    record: 'Registrar resultado',
    resume: 'Abrir el paso registrado',
    active:
      'El problema seleccionado se mantiene entre artículos. Revisa la selección antes de registrar otro problema.',
    rollback: 'Lista de ajustes temporales',
    setting: 'Ajuste modificado',
    original: 'Valor original',
    restore: 'Cómo restaurarlo',
    pending: 'Pendiente de restaurar',
    restored: 'Restaurado',
    kept: 'Mantener: se identificó como causa',
    add: 'Añadir ajuste',
    noSettings: 'No hay ajustes temporales registrados.',
    summary: 'Resumen para pedir ayuda: vista previa y copia',
    include: 'Elige qué incluir',
    includeGame: 'Juego',
    includeSymptoms: 'Síntomas (texto original)',
    includePc: 'Especificaciones del PC',
    includeAttempts: 'Intentos y resultados (texto original)',
    includeNotes: 'Ajustes y notas (texto original)',
    language: 'Idioma del resumen',
    review:
      'El texto libre se excluye por defecto para omitir nombres, rutas y datos de cuentas. Si lo incluyes, elimina los datos privados en la vista previa antes de copiar. El ocultamiento automático no garantiza su eliminación completa.',
    untranslated:
      'Los textos del usuario y títulos de pasos siguientes son originales; no se han traducido automáticamente.',
    preview: 'Vista previa editable',
    copy: 'Copiar texto',
    copied: 'Copiado. Pégalo tú mismo en Discord, Reddit o el soporte oficial.',
    copyError: 'No se pudo copiar. Selecciona el texto y cópialo manualmente.',
    updates: 'Novedades verificadas para problemas sin resolver',
    emptyUpdates:
      'No hay novedades verificadas que coincidan con tus problemas guardados sin resolver. Esto no significa que estén corregidos.',
    official: 'Corrección oficial',
    workaround: 'Solución alternativa verificada',
    evidence: 'Fuente',
    verified: 'Verificado el',
    mark: 'Marcar estas novedades como leídas',
    updateHint:
      'Se muestra por separado de las noticias generales de Steam. Coincide con el juego y el síntoma del artículo guardado; una fecha de actualización no demuestra una corrección. Revisa las versiones y condiciones aplicables.',
  },
};
