/** Explicit related article allowlist; adds a CTA without touching article data. */
export const diagnosisGuideSlugs = new Set([
  'steam-game-not-launching',
  'pc-game-crash',
  'black-screen',
  'pc-game-freezes',
  'low-fps',
  'stutter-fix',
  'low-gpu-usage',
  'vram-shortage',
  'directx-error',
  'visual-c-runtime-error',
  'gpu-driver-update',
  'verify-steam-files',
  'steam-disk-write-error',
  'steam-cloud-sync-error',
  'no-game-audio',
  'steam-input-controller',
  'controller-double-input',
  'remove-mods-safely',
  'reset-config-file',
  'bsod-while-gaming',
  'pc-shuts-down-while-gaming',
]);
