import type { Locale } from '@/lib/i18n';

// Interface text for the translated pages (header, footer and page parts).

export const ui = {
  en: {
    brandTagline: 'PC game troubleshooting',
    mainNav: 'Main navigation',
    footerNav: 'Footer navigation',
    mobileNav: 'Mobile navigation',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    explore: 'Explore Gemnao',
    home: 'Home',
    inJapanese: ' (Japanese)',
    about: 'About',
    privacy: 'Privacy',
    terms: 'Terms',
    discordServers: 'Discord servers',
    pcWindows: 'PC & Windows',
    contact: 'Contact',
    footerTagline:
      'Step-by-step fixes for PC games, based on official publisher and store information.',
    trademarks: 'Game names and trademarks belong to their respective owners.',
    homeKicker: 'PC GAME FIXES',
    homeTitle: 'Fix PC game problems, one step at a time',
    homeBody:
      'Save locations, launch errors and crashes for popular PC games. Every guide follows the publisher’s own support steps and links to them, so you can check the source.',
    homeGames: 'Games',
    homeArticles: 'Step-by-step guides',
    homeNote:
      'These pages are written for English readers from the same official sources as our Japanese guides. Menu names can differ slightly between game versions.',
    gameLabel: 'PC troubleshooting guide',
    lastChecked: 'Last checked',
    contents: 'On this page',
    guides: 'Step-by-step guides',
    checklist: 'If the game will not start',
    checklistIntro:
      'Try one item at a time and test the game after each change, so you know what fixed it.',
    saves: 'Save and settings locations',
    saveData: 'Save data',
    installFolder: '<game folder>',
    config: 'Settings files',
    openPath:
      'Press Windows + R, paste a path that starts with %APPDATA%, %LOCALAPPDATA% or %USERPROFILE%, and press Enter. Replace anything in angle brackets, such as <Steam ID>, with your own folder name.',
    requirements: 'Official system requirements (Steam)',
    specItem: 'Component',
    minimum: 'Minimum',
    recommended: 'Recommended',
    os: 'OS',
    cpu: 'Processor',
    gpu: 'Graphics',
    ram: 'Memory',
    storage: 'Storage',
    ssdRequired: 'SSD required',
    ssdRecommended: 'SSD recommended',
    ssdPreferred: 'SSD preferred',
    requirementsNote:
      'From the Steam store page. Requirements can change after updates, so check the store before buying hardware.',
    languages: 'Language support (Steam)',
    language: 'Language',
    interfaceText: 'Interface and subtitles',
    fullAudio: 'Full audio',
    yes: 'Yes',
    no: 'No',
    langNames: {
      ja: 'Japanese',
      en: 'English',
      zh: 'Simplified Chinese',
      es: 'Spanish (Spain)',
    },
    references: 'Official sources',
    summary: 'The short answer',
    quickFacts: 'Key facts',
    diagnosis: 'Find your symptom',
    symptom: 'What you see',
    cause: 'Likely cause',
    step: 'Go to',
    steps: 'Fixes, in order',
    stepLabel: 'Step',
    time: 'Time',
    avoid: 'Avoid',
    cautions: 'If it still does not work',
    faq: 'FAQ',
    copyLabels: {
      copy: 'Copy',
      copied: 'Copied',
      aria: 'Copy path',
      failed: 'Select the path and copy it manually',
    },
    sourcePolicy:
      'We checked these official pages and wrote the steps in our own words. Follow the publisher’s page if it has changed.',
    japaneseVersion: 'Japanese version of this page',
  },
  zh: {
    brandTagline: 'PC 游戏故障排查',
    mainNav: '主导航',
    footerNav: '页脚导航',
    mobileNav: '移动端导航',
    openMenu: '打开菜单',
    closeMenu: '关闭菜单',
    explore: '浏览 Gemnao',
    home: '首页',
    inJapanese: '（日语）',
    about: '关于本站',
    privacy: '隐私政策',
    terms: '使用条款',
    discordServers: 'Discord 服务器',
    pcWindows: 'PC 与 Windows',
    contact: '联系我们',
    footerTagline:
      '依据发行商与商店官方信息，按步骤整理的 PC 游戏故障解决方法。',
    trademarks: '游戏名称与商标归各自权利人所有。',
    homeKicker: 'PC 游戏故障解决',
    homeTitle: '一步一步解决 PC 游戏问题',
    homeBody:
      '汇总热门 PC 游戏的存档位置、无法启动与崩溃问题。每篇指南都依据发行商的官方支持步骤编写，并附上原始链接，方便核对。',
    homeGames: '游戏',
    homeArticles: '分步指南',
    homeNote:
      '这些页面依据与日语版相同的官方资料，为中文读者重新编写。菜单名称可能因游戏版本而略有不同。',
    gameLabel: 'PC 故障排查指南',
    lastChecked: '最后核对',
    contents: '本页内容',
    guides: '分步指南',
    checklist: '游戏无法启动时',
    checklistIntro:
      '每次只尝试一项，并在每次修改后启动游戏测试，这样才能知道是哪一步解决了问题。',
    saves: '存档与设置文件位置',
    saveData: '存档',
    installFolder: '<游戏安装文件夹>',
    config: '设置文件',
    openPath:
      '按 Windows + R，粘贴以 %APPDATA%、%LOCALAPPDATA% 或 %USERPROFILE% 开头的路径，然后按回车。尖括号中的内容（如 <Steam ID>）请替换为你自己的文件夹名称。',
    requirements: '官方配置需求（Steam）',
    specItem: '项目',
    minimum: '最低配置',
    recommended: '推荐配置',
    os: '操作系统',
    cpu: '处理器',
    gpu: '显卡',
    ram: '内存',
    storage: '存储空间',
    ssdRequired: '需要 SSD',
    ssdRecommended: '建议使用 SSD',
    ssdPreferred: '最好使用 SSD',
    requirementsNote:
      '摘自 Steam 商店页面。配置需求可能随更新变化，购买硬件前请先查看商店页面。',
    languages: '语言支持（Steam）',
    language: '语言',
    interfaceText: '界面与字幕',
    fullAudio: '完整语音',
    yes: '支持',
    no: '不支持',
    langNames: {
      ja: '日语',
      en: '英语',
      zh: '简体中文',
      es: '西班牙语（西班牙）',
    },
    references: '官方资料',
    summary: '简要结论',
    quickFacts: '要点',
    diagnosis: '按症状查找',
    symptom: '出现的情况',
    cause: '可能的原因',
    step: '前往',
    steps: '解决步骤（按顺序）',
    stepLabel: '步骤',
    time: '所需时间',
    avoid: '请避免',
    cautions: '仍然无法解决时',
    faq: '常见问题',
    copyLabels: {
      copy: '复制',
      copied: '已复制',
      aria: '复制路径',
      failed: '请选中路径后手动复制',
    },
    sourcePolicy:
      '我们核对了以下官方页面，并用自己的文字整理步骤。若官方页面已更新，请以官方为准。',
    japaneseVersion: '本页的日语版',
  },
  es: {
    brandTagline: 'Soluciones para juegos de PC',
    mainNav: 'Navegación principal',
    footerNav: 'Navegación del pie de página',
    mobileNav: 'Navegación móvil',
    openMenu: 'Abrir menú',
    closeMenu: 'Cerrar menú',
    explore: 'Explorar Gemnao',
    home: 'Inicio',
    inJapanese: ' (en japonés)',
    about: 'Acerca de',
    privacy: 'Privacidad',
    terms: 'Condiciones',
    discordServers: 'Servidores de Discord',
    pcWindows: 'PC y Windows',
    contact: 'Contacto',
    footerTagline:
      'Soluciones paso a paso para juegos de PC, basadas en la información oficial de editores y tiendas.',
    trademarks:
      'Los nombres y marcas de los juegos pertenecen a sus respectivos titulares.',
    homeKicker: 'SOLUCIONES PARA JUEGOS DE PC',
    homeTitle: 'Soluciona los problemas de tus juegos de PC paso a paso',
    homeBody:
      'Ubicación de partidas, errores de inicio y cierres de juegos populares de PC. Cada guía sigue los pasos del soporte oficial del editor y enlaza a ellos para que puedas comprobar la fuente.',
    homeGames: 'Juegos',
    homeArticles: 'Guías paso a paso',
    homeNote:
      'Estas páginas están escritas para lectores en español a partir de las mismas fuentes oficiales que nuestras guías en japonés. Los nombres de los menús pueden variar ligeramente según la versión del juego.',
    gameLabel: 'Guía de solución de problemas para PC',
    lastChecked: 'Última revisión',
    contents: 'En esta página',
    guides: 'Guías paso a paso',
    checklist: 'Si el juego no inicia',
    checklistIntro:
      'Prueba una cosa cada vez e inicia el juego después de cada cambio para saber qué lo ha solucionado.',
    saves: 'Ubicación de partidas y ajustes',
    saveData: 'Partidas',
    installFolder: '<carpeta del juego>',
    config: 'Archivos de ajustes',
    openPath:
      'Pulsa Windows + R, pega una ruta que empiece por %APPDATA%, %LOCALAPPDATA% o %USERPROFILE% y pulsa Intro. Sustituye lo que aparece entre < >, como <Steam ID>, por el nombre de tu propia carpeta.',
    requirements: 'Requisitos oficiales (Steam)',
    specItem: 'Componente',
    minimum: 'Mínimos',
    recommended: 'Recomendados',
    os: 'Sistema operativo',
    cpu: 'Procesador',
    gpu: 'Gráficos',
    ram: 'Memoria',
    storage: 'Almacenamiento',
    ssdRequired: 'SSD obligatorio',
    ssdRecommended: 'SSD recomendado',
    ssdPreferred: 'SSD preferible',
    requirementsNote:
      'Según la página de Steam. Los requisitos pueden cambiar con las actualizaciones; consulta la tienda antes de comprar hardware.',
    languages: 'Idiomas (Steam)',
    language: 'Idioma',
    interfaceText: 'Interfaz y subtítulos',
    fullAudio: 'Voces',
    yes: 'Sí',
    no: 'No',
    langNames: {
      ja: 'Japonés',
      en: 'Inglés',
      zh: 'Chino simplificado',
      es: 'Español (España)',
    },
    references: 'Fuentes oficiales',
    summary: 'Respuesta rápida',
    quickFacts: 'Datos clave',
    diagnosis: 'Busca tu síntoma',
    symptom: 'Qué ocurre',
    cause: 'Causa probable',
    step: 'Ir a',
    steps: 'Soluciones, en orden',
    stepLabel: 'Paso',
    time: 'Tiempo',
    avoid: 'Evita',
    cautions: 'Si sigue sin funcionar',
    faq: 'Preguntas frecuentes',
    copyLabels: {
      copy: 'Copiar',
      copied: 'Copiado',
      aria: 'Copiar ruta',
      failed: 'Selecciona la ruta y cópiala a mano',
    },
    sourcePolicy:
      'Hemos revisado estas páginas oficiales y redactado los pasos con nuestras propias palabras. Si la página del editor ha cambiado, sigue la versión oficial.',
    japaneseVersion: 'Versión en japonés de esta página',
  },
} satisfies Record<Locale, Record<string, unknown>>;

export type LocaleUi = (typeof ui)['en'];
